Repository Goorm-Lucky7/Dart_FE, pull requests merged in 2024-07, with the labels that each got.

#95 [PR] 실시간 기능 및 기타 오류 해결
  src/apis/chat.ts
  src/pages/chatModal/components/chat/ChatMenu.tsx
  src/pages/chatModal/components/chat/Message.tsx
  src/pages/chatModal/components/chat/styles.ts
  src/pages/chatModal/components/viewer/Member.tsx
  src/pages/chatModal/components/viewer/ViewerMenu.tsx
  src/pages/chatModal/components/viewer/styles.ts
  src/pages/chatModal/hooks/useChatScroll.ts
  src/pages/chatModal/hooks/useStomp.ts
  src/pages/chatModal/index.tsx
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryInfo/styles.ts
  src/pages/payment/components/sDiscount/index.tsx
  src/pages/payment/components/sDiscount/styles.ts
  src/pages/payment/components/sOrder/index.tsx
  src/pages/payment/index.tsx
  src/pages/post/components/inputs/TagsInput.tsx
  src/pages/post/index.tsx
  src/stores/modal.ts
  src/types/chat.ts
Labels: 🪲 Bug, ✨ Fix

#96 [PR] 이미지 압축 학습, UI 테스트 반영
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/gallery.ts
  src/assets/images/mainLogo.png
  src/components/icon/index.tsx
  src/consts/agree.ts
  src/hooks/useCompress.ts
  src/pages/editMemberInfo/hooks/usePutMember.ts
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/gallery/components/galleryTemplate/scroll/index.tsx
  src/pages/gallery/components/shareModal/index.tsx
  src/pages/gallery/hooks/shareKakao.ts
  src/pages/gallery/index.tsx
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryInfo/styles.ts
  src/pages/main/components/kakaoMap/index.tsx
  src/pages/main/components/kakaoMap/styles.ts
  src/pages/post/components/address/index.tsx
  src/pages/post/components/address/styles.ts
  src/pages/post/components/index.ts
  src/pages/post/components/progressModal/index.tsx
  src/pages/post/components/stepThree/index.tsx
  src/pages/post/components/stepThree/styles.ts
  src/pages/post/hooks/usePostGalleries.ts
  src/pages/post/index.tsx
  src/pages/post/styles.ts
  src/types/address.ts
  src/types/post.ts
Labels: ✨ Fix, 🎁 Feature, 🎩 Style, 🥃 Chore

#100 [PR] 반응형 UI 및 마무리
  src/App.tsx
  src/components/GalleryInfoPortal.tsx
  src/components/UserCircle.tsx
  src/components/footer/styles.ts
  src/pages/editMemberInfo/components/editMemberForm/index.tsx
  src/pages/editMemberInfo/components/editMemberForm/styles.ts
  src/pages/editMemberInfo/components/editMemberHeader/index.tsx
  src/pages/editMemberInfo/components/editMemberHeader/styles.ts
  src/pages/editMemberInfo/hooks/usePutMember.ts
  src/pages/gallery/components/galleryDetail/styles.ts
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/gallery/components/galleryHeader/styles.ts
  src/pages/gallery/components/galleryTemplate/grid/index.tsx
  src/pages/gallery/components/galleryTemplate/grid/styles.ts
  src/pages/gallery/components/galleryTemplate/mobile/index.tsx
  src/pages/gallery/components/galleryTemplate/mobile/styles.ts
  src/pages/gallery/components/galleryTemplate/rotate/index.tsx
  src/pages/gallery/components/galleryTemplate/rotate/styles.ts
  src/pages/gallery/components/galleryTemplate/scroll/card/styles.ts
  src/pages/gallery/components/galleryTemplate/slide/index.tsx
  src/pages/gallery/components/galleryTemplate/slide/styles.ts
  src/pages/gallery/hooks/selectTemplate.tsx
  src/pages/intro/components/introduce/index.tsx
  src/pages/intro/components/introduce/styles.ts
  src/pages/intro/styles.ts
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryInfo/styles.ts
  src/pages/main/components/galleryItem/index.tsx
  src/pages/main/components/galleryItem/styles.ts
  src/pages/main/components/kakaoMap/styles.ts
  src/pages/main/hooks/starRate.tsx
  src/pages/main/index.tsx
  src/pages/post/components/address/index.tsx
  src/pages/post/components/address/styles.ts
  src/pages/post/index.tsx
  src/stores/modal.ts
  src/styles/breakpoints.ts
  src/types/gallery.ts
  src/types/post.ts
Labels: ✨ Fix, 🎁 Feature, 🎩 Style, 🥃 Chore

#101 [PR] 생성 페이지 반응형 구현
  src/components/icon/index.tsx
  src/pages/chatModal/components/chat/ChatMenu.tsx
  src/pages/chatModal/components/viewer/ViewerMenu.tsx
  src/pages/chatModal/hooks/useStomp.ts
  src/pages/chatModal/index.tsx
  src/pages/memberInfo/components/exhibition/styles.ts
  src/pages/memberInfo/components/menu/styles.ts
  src/pages/memberInfo/index.tsx
  src/pages/memberInfo/styles.ts
  src/pages/post/components/address/index.tsx
  src/pages/post/components/address/styles.ts
  src/pages/post/components/guide/index.tsx
  src/pages/post/components/guide/styles.ts
  src/pages/post/components/index.ts
  src/pages/post/components/inputs/TagsInput.tsx
  src/pages/post/components/inputs/styles.ts
  src/pages/post/components/stepAlpha/Address.tsx
  src/pages/post/components/stepAlpha/index.tsx
  src/pages/post/components/stepAlpha/styles.ts
  src/pages/post/components/stepOne/index.tsx
  src/pages/post/components/stepOne/styles.ts
  src/pages/post/components/stepThree/index.tsx
  src/pages/post/components/stepThree/styles.ts
  src/pages/post/components/stepTwo/index.tsx
  src/pages/post/components/stepTwo/styles.ts
  src/pages/post/components/stepZero/index.tsx
  src/pages/post/components/stepZero/styles.ts
  src/pages/post/index.tsx
  src/pages/post/styles.ts
  src/styles/breakpoints.ts
  src/styles/layout.ts
  src/types/chat.ts
Labels: ✨ Fix, 🎩 Style

#99 [PR] mian페이지 반응형 UI 작업
  pnpm-lock.yaml
  src/App.tsx
  src/apis/instance.ts
  src/apis/member.ts
  src/components/AlertPortal.tsx
  src/components/NotificationPortal.tsx
  src/components/alert/index.tsx
  src/components/alert/styles.ts
  src/components/icon/index.tsx
  src/components/inputField/index.tsx
  src/components/navbar/index.tsx
  src/components/navbar/styles.ts
  src/components/notification/index.tsx
  src/components/pageButtons/index.tsx
  src/consts/navbar.ts
  src/hooks/useDisabledScroll.ts
  src/hooks/useGetMediaQuerySize.ts
  src/hooks/useNotification.ts
  src/hooks/useOnError.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useTimer.ts
  src/pages/chatModal/components/chat/Message.tsx
  src/pages/chatModal/hooks/useChatScroll.ts
  src/pages/editMemberInfo/hooks/usePutMember.ts
  src/pages/event/components/priorityCoupon/index.tsx
  src/pages/event/hooks/usePostPriorityCoupon.ts
  src/pages/gallery/components/galleryTemplate/scroll/index.tsx
  src/pages/login/components/loginLayout/styles.ts
  src/pages/login/hooks/usePostLogin.ts
  src/pages/login/styles.ts
  src/pages/main/components/buttonNLine/index.tsx
  src/pages/main/components/buttonNLine/styles.ts
  src/pages/main/components/fallback/GalleryListFallback.tsx
  src/pages/main/components/fallback/styles.ts
  src/pages/main/components/filter/index.tsx
  src/pages/main/components/filter/styles.ts
  src/pages/main/components/galleryItem/styles.ts
  src/pages/main/components/galleryList/index.tsx
  src/pages/main/components/galleryList/styles.ts
  src/pages/main/components/index.ts
  src/pages/main/components/postButton/index.tsx
  src/pages/main/components/postButton/styles.ts
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/pages/post/index.tsx
  src/pages/post/styles.ts
  src/pages/review/components/reviewGalleryInfo/index.tsx
  src/pages/review/components/reviewItem/index.tsx
  src/stores/filter.ts
  src/stores/member.ts
  src/stores/modal.ts
  src/styles/breakpoints.ts
  src/styles/globalStyles.ts
  src/styles/layout.ts
  src/types/address.ts
  src/types/notification.ts
  src/types/review.ts
Labels: 🪲 Bug, ✨ Fix, 🎩 Style

#106 [PR] hotfix: 경로 이동 오류, kakao api 스크립트 설정 부분 위치 변경
  index.html
  pnpm-lock.yaml
  src/App.tsx
  src/components/GalleryInfoPortal.tsx
  src/components/alert/styles.ts
  src/pages/gallery/components/shareModal/index.tsx
  src/pages/gallery/hooks/selectTemplate.tsx
  src/pages/gallery/index.tsx
  src/pages/gallery/styles.ts
  src/pages/main/components/galleryInfo/index.tsx
Labels: 🪲 Bug, ✨ Fix, 🔧 Refactor, 🎩 Style

#104 [PR] 결제 오류 수정
  src/apis/payment.ts
  src/pages/chatModal/components/viewer/ViewerMenu.tsx
  src/pages/gallery/index.tsx
  src/pages/payment/components/sDiscount/index.tsx
  src/pages/payment/components/sOrder/index.tsx
  src/pages/payment/components/sTotalCost/index.tsx
  src/pages/payment/hooks/usePostPayment.ts
  src/pages/post/index.tsx
Labels: 🪲 Bug

#114 [PR] HotFix: 클래스명 변경
  src/pages/info/index.tsx
  src/pages/info/styles.ts
Labels: 🥃 Chore

#117 [PR] 저작권 침해 방지 마련, UI 디테일 수정
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/images/introduceItem1.png
  src/assets/images/introduceItem2.png
  src/assets/images/introduceItem3.png
  src/assets/images/logoCol.png
  src/assets/images/mainLogo.png
  src/components/GalleryDetailPortal.tsx
  src/components/GalleryInfoPortal.tsx
  src/components/alert/index.tsx
  src/components/alert/styles.ts
  src/components/icon/index.tsx
  src/hooks/useCustomNavigate.ts
  src/pages/gallery/components/galleryDetail/styles.ts
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/gallery/components/galleryHeader/styles.ts
  src/pages/gallery/components/galleryTemplate/mobile/index.tsx
  src/pages/gallery/components/galleryTemplate/mobile/styles.ts
  src/pages/gallery/components/galleryTemplate/rotate/index.tsx
  src/pages/gallery/components/galleryTemplate/slide/styles.ts
  src/pages/gallery/index.tsx
  src/pages/info/index.tsx
  src/pages/info/styles.ts
  src/pages/intro/components/introduce/styles.ts
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryInfo/styles.ts
  src/pages/main/components/kakaoMap/index.tsx
  src/pages/main/components/kakaoMap/styles.ts
  src/pages/post/index.tsx
  src/stores/modal.ts
  src/styles/button.ts
Labels: 🪲 Bug, ✨ Fix, 🎁 Feature, 🎩 Style, 🥃 Chore

#116 [PR] 반응형 UI 구현 및 마무리
  src/components/dropZone/index.tsx
  src/pages/chatModal/components/chat/ChatMenu.tsx
  src/pages/chatModal/components/chat/Message.tsx
  src/pages/chatModal/components/chat/styles.ts
  src/pages/chatModal/hooks/useStomp.ts
  src/pages/chatModal/index.tsx
  src/pages/chatModal/styles.ts
  src/pages/memberInfo/components/exhibition/Ticket.tsx
  src/pages/memberInfo/components/exhibition/index.tsx
  src/pages/memberInfo/components/exhibition/styles.ts
  src/pages/memberInfo/components/info/index.tsx
  src/pages/memberInfo/components/info/style.ts
  src/pages/memberInfo/components/info/styles.ts
  src/pages/memberInfo/components/menu/styles.ts
  src/pages/memberInfo/components/purchase/styles.ts
  src/pages/memberInfo/styles.ts
  src/pages/payment/components/motion/styles.ts
  src/pages/payment/components/sDiscount/styles.ts
  src/pages/payment/components/sOrder/Ticket.tsx
  src/pages/payment/components/sOrder/index.tsx
  src/pages/payment/components/sOrder/styles.ts
  src/pages/payment/fail/index.tsx
  src/pages/payment/fail/styles.ts
  src/pages/payment/index.tsx
  src/pages/payment/styles.ts
  src/pages/payment/success/index.tsx
  src/pages/payment/success/styles.ts
  src/pages/post/components/stepOne/index.tsx
  src/pages/post/components/stepOne/styles.ts
  src/pages/post/components/stepThree/styles.ts
  src/pages/post/components/stepZero/index.tsx
  src/pages/post/components/stepZero/styles.ts
  src/pages/post/index.tsx
  src/styles/breakpoints.ts
Labels: ✨ Fix, 🎩 Style, 🥃 Chore

#120 [PR] gallery websocket 오류 해결
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/gallery/index.tsx
Labels: 🪲 Bug

#121 [PR] 피드백 반영하여 ui 수정
  src/pages/payment/components/sDiscount/index.tsx
  src/pages/payment/components/sDiscount/styles.ts
  src/pages/payment/styles.ts
  src/pages/post/components/inputs/TagsInput.tsx
  src/pages/post/components/inputs/styles.ts
Labels: 🎩 Style

#122 [PR] contact 페이지 1차 작성, 디테일 UI 수정
  package.json
  pnpm-lock.yaml
  src/consts/teamUser.ts
  src/pages/contact/index.tsx
  src/pages/contact/styles.ts
  src/pages/editMemberInfo/components/errorData/index.tsx
  src/pages/gallery/components/galleryTemplate/mobile/index.tsx
  src/pages/gallery/index.tsx
  src/pages/index.ts
  src/routes/index.ts
Labels: ✨ Fix, 🎁 Feature, 🎩 Style, 🥃 Chore

#127 [PR] 템플릿 3D 모드 추가 및 디테일 UI 수정
  package.json
  pnpm-lock.yaml
  src/apis/instance.ts
  src/assets/images/galleryDefault.png
  src/assets/images/luckySeven.png
  src/components/GalleryInfoPortal.tsx
  src/consts/teamUser.ts
  src/consts/threed.ts
  src/pages/contact/index.tsx
  src/pages/contact/styles.ts
  src/pages/gallery/components/galleryTemplate/index.tsx
  src/pages/gallery/components/galleryTemplate/threed/index.tsx
  src/pages/gallery/components/galleryTemplate/threed/styles.ts
  src/pages/gallery/hooks/selectTemplate.tsx
  src/pages/gallery/index.tsx
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryItem/styles.ts
  src/pages/post/components/progressModal/index.tsx
  src/pages/post/components/progressModal/styles.ts
  src/pages/post/index.tsx
Labels: ✨ Fix, 🎁 Feature, 🎩 Style, 🥃 Chore

#129 [PR] 변경사항 수정
  src/assets/images/template5.png
  src/components/icon/index.tsx
  src/pages/chatModal/styles.ts
  src/pages/gallery/index.tsx
  src/pages/memberInfo/components/exhibition/index.tsx
  src/pages/post/components/stepThree/index.tsx
  src/pages/post/components/stepTwo/index.tsx
  src/pages/post/components/stepTwo/styles.ts
  src/pages/post/index.tsx
  src/types/post.ts
Labels: ✨ Fix, 🥃 Chore

#130 [PR]hotfix: 로딩 상태 변경
  src/pages/gallery/components/galleryTemplate/threed/index.tsx
Labels: ✨ Fix

#132 [PR] hotfix: doubleClick에 대한 조건 설정
  src/pages/gallery/components/galleryTemplate/threed/index.tsx
Labels: 🪲 Bug

#133 [PR] hotfix: 주석 풀기
  src/pages/gallery/index.tsx
Labels: 🪲 Bug

#134 [PR] 템플릿 적용 수정
  src/pages/post/components/stepThree/index.tsx
Labels: ✨ Fix

#136 [Deploy] reissue 수정 및 3js 탬플릿 추가
  .github/workflows/front-build.yaml
  package.json
  pnpm-lock.yaml
  src/apis/instance.ts
  src/apis/search.ts
  src/assets/images/galleryDefault.png
  src/assets/images/luckySeven.png
  src/assets/images/template5.png
  src/components/GalleryInfoPortal.tsx
  src/components/icon/index.tsx
  src/components/navbar/index.tsx
  src/consts/teamUser.ts
  src/consts/threed.ts
  src/hooks/useNotification.ts
  src/pages/chatModal/styles.ts
  src/pages/contact/index.tsx
  src/pages/contact/styles.ts
  src/pages/gallery/components/galleryTemplate/index.tsx
  src/pages/gallery/components/galleryTemplate/threed/index.tsx
  src/pages/gallery/components/galleryTemplate/threed/styles.ts
  src/pages/gallery/hooks/selectTemplate.tsx
  src/pages/gallery/index.tsx
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryItem/index.tsx
  src/pages/main/components/galleryItem/styles.ts
  src/pages/main/components/galleryList/index.tsx
  src/pages/main/components/keywordFilter/index.tsx
  src/pages/main/hooks/useGetSearchDatas.ts
  src/pages/main/index.tsx
  src/pages/memberInfo/components/exhibition/index.tsx
  src/pages/post/components/progressModal/index.tsx
  src/pages/post/components/progressModal/styles.ts
  src/pages/post/components/stepThree/index.tsx
  src/pages/post/components/stepTwo/index.tsx
  src/pages/post/components/stepTwo/styles.ts
  src/pages/post/index.tsx
  src/stores/member.ts
  src/types/post.ts
Labels: 🛰️ Deploy

#137 Develop/endui
  src/pages/gallery/index.tsx
  src/pages/post/index.tsx
Labels: 🪲 Bug, ✨ Fix, 🔧 Refactor, 🎩 Style, 🥃 Chore

#138 [PR] fix: 이미지 저작권 관련 이용약관 내용 수정
  src/consts/agree.ts
  src/pages/post/index.tsx
Labels: 🥃 Chore

#139 [PR] hotfix: 이미지 담겨져있지 않으면 json형태로 null로 보내기
  src/apis/member.ts
Labels: 🪲 Bug, ✨ Fix

#140 [Deploy] 이용약관 내역 및 POST 요청 수정 관련 개선
  src/apis/member.ts
  src/consts/agree.ts
  src/pages/gallery/index.tsx
  src/pages/post/index.tsx
Labels: 🛰️ Deploy

#142 [PR] hotfix: 정보수정 api 원상태로 되돌리기
  src/apis/member.ts
  src/pages/editMemberInfo/components/editMemberForm/index.tsx
Labels: 🪲 Bug, 🥃 Chore

#143 Fix: 로그아웃을 비롯한 reissue 관련 로직 수정
  pnpm-lock.yaml
  src/apis/gallery.ts
  src/apis/instance.ts
  src/apis/member.ts
  src/components/CategoryPortal.tsx
  src/components/ProgressPortal.tsx
  src/components/alert/index.tsx
  src/components/navbar/index.tsx
  src/consts/signup.ts
  src/hooks/useNotification.ts
  src/pages/callback/hooks/usePostSocialLogin.ts
  src/pages/callback/index.tsx
  src/pages/editMemberInfo/hooks/usePutMember.ts
  src/pages/index.ts
  src/pages/login/components/socialButtons/index.tsx
  src/pages/main/components/categoryModal/index.tsx
  src/pages/main/components/galleryList/index.tsx
  src/pages/post/hooks/usePostGalleries.ts
  src/pages/post/hooks/useUploadingBar.ts
  src/pages/post/index.tsx
  src/routes/index.ts
  src/stores/modal.ts
Labels: 🪲 Bug, ✨ Fix, 🎩 Style

#144 [Deploy] post시 progressbar 수정 및 reissue 및 로그아웃 수정
  pnpm-lock.yaml
  src/apis/gallery.ts
  src/apis/instance.ts
  src/apis/member.ts
  src/components/CategoryPortal.tsx
  src/components/ProgressPortal.tsx
  src/components/alert/index.tsx
  src/components/navbar/index.tsx
  src/consts/signup.ts
  src/hooks/useNotification.ts
  src/pages/callback/hooks/usePostSocialLogin.ts
  src/pages/callback/index.tsx
  src/pages/editMemberInfo/components/editMemberForm/index.tsx
  src/pages/editMemberInfo/hooks/usePutMember.ts
  src/pages/index.ts
  src/pages/login/components/socialButtons/index.tsx
  src/pages/main/components/categoryModal/index.tsx
  src/pages/main/components/galleryList/index.tsx
  src/pages/post/hooks/usePostGalleries.ts
  src/pages/post/hooks/useUploadingBar.ts
  src/pages/post/index.tsx
  src/routes/index.ts
  src/stores/modal.ts
Labels: 🛰️ Deploy

#146 [PR] hotfix: 누르자마자 모달창 띄우고, post 요청에 대한 퍼센트 보여주기
  src/apis/gallery.ts
  src/pages/post/hooks/usePostGalleries.ts
  src/pages/post/index.tsx
Labels: 🪲 Bug, ✨ Fix

#147 [deploy] 프로그레스바 요청에 대한 퍼센트 반영
  src/apis/gallery.ts
  src/pages/post/hooks/usePostGalleries.ts
  src/pages/post/index.tsx
Labels: 🪲 Bug, ✨ Fix

#151 [PR] chore: 리드미 내용 없애기
  README.md
Labels: 🥃 Chore

#152 [Deploy]
  README.md
  src/apis/gallery.ts
  src/pages/main/hooks/useGetGalleries.ts
Labels: 🛰️ Deploy

#154 [deploy] 전시 생성, 3D 템플릿에 문구 추가
  README.md
  src/pages/gallery/components/galleryTemplate/threed/index.tsx
  src/pages/gallery/components/galleryTemplate/threed/styles.ts
  src/pages/post/components/stepThree/index.tsx
  src/pages/post/components/stepThree/styles.ts
Labels: ✨ Fix, 🎩 Style

#155 [PR] 채팅 날짜 정의 추가, 전시 생성시 등록 오류 에러 핸들링
  README.md
  src/consts/postValidation.ts
  src/pages/chatModal/components/chat/ChatMenu.tsx
  src/pages/payment/success/index.tsx
  src/pages/post/components/stepZero/index.tsx
  src/pages/post/hooks/useHandleErrors.ts
  src/pages/post/index.tsx
  src/types/chat.ts
  src/utils/formatDateforChat.ts
  src/utils/formatDateforPost.ts
  src/utils/parseDate.ts
Labels: 🪲 Bug, ✨ Fix, 🥃 Chore

#156 [Deploy]
  README.md
  src/consts/postValidation.ts
  src/pages/chatModal/components/chat/ChatMenu.tsx
  src/pages/payment/success/index.tsx
  src/pages/post/components/stepZero/index.tsx
  src/pages/post/hooks/useHandleErrors.ts
  src/pages/post/index.tsx
  src/types/chat.ts
  src/utils/formatDateforChat.ts
  src/utils/formatDateforPost.ts
  src/utils/parseDate.ts
Labels: 🛰️ Deploy

#159 [PR] 포탈 모듈화 및 적용
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/CategoryPortal.tsx
  src/components/ChatPortal.tsx
  src/components/ContentPortal.tsx
  src/components/CouponPortal.tsx
  src/components/GalleryInfoPortal.tsx
  src/components/LoginPortal.tsx
  src/components/SignupCheckPortal.tsx
  src/components/index.ts
  src/pages/chatModal/components/viewer/Member.tsx
  src/pages/chatModal/index.tsx
  src/pages/gallery/components/galleryHeader/index.tsx
  src/pages/gallery/index.tsx
  src/pages/main/components/buttonBar/index.tsx
  src/pages/main/components/filter/index.tsx
  src/pages/main/components/galleryInfo/index.tsx
  src/pages/main/components/galleryItem/index.tsx
  src/pages/main/index.tsx
  src/pages/payment/components/sDiscount/index.tsx
  src/pages/signup/components/checkModal/index.tsx
  src/pages/signup/components/signupForm/index.tsx
  src/pages/signup/index.tsx
  src/stores/modal.ts
  src/types/gallery.ts
Labels: 🔧 Refactor
